
services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo_data:/data/db
  valkey:
    image: valkey/valkey:latest
    container_name: valkey_db
    ports:
      - 6379:6379
    volumes:
      - valkey_data:/usr/local/etc/valkey
volumes:
  mongo_data:
  valkey_data: