[project]
name = "testing-clawdbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=25.1.0",
    "fastapi[standard]>=0.128.0",
    "pymongo>=4.16.0",
    "uvicorn[standard]>=0.24.0",
]
